### ISSUE TITLE
A few bugs with `PossibleValues`field

### ISSUE THREAD

**Issue by crlf0710** [pdf-association/arlington-pdf-model#12] opened 2022-02-05 06:36 UTC
Bug in `GraphicsStateParameter.@LW`: Its `PossibleValues` field says `[fn:Eval(@LW>0)]`, but line width is non-negative and zero is meaningful. I guess it should be `[fn:Eval(@LW>=0)]` instead.

**Comment by crlf0710** [comment] 2022-02-05 06:38
The same might apply to `GraphicsStateParameter.@ML` as well?

**Comment by crlf0710** [comment] 2022-02-05 06:49
In `Annot*.{@CA, @ca}`, their PossibleValues currently is `[fn:Eval((@ca>=0.0) && (@ca<1.0))]` but should be `[fn:Eval((@ca>=0.0) && (@ca<=1.0))]`, since 1.0 is default value and supported.

**Comment by crlf0710** [comment] 2022-02-05 07:53
In `Projection.@OS`, its PossibleValues currently is `[fn:Eval(@OS>=0)]`, but zero is invalid here, since the spec specifies this is a positive number.

In `Projection.@PS`, it should also be positive when using the `number` form, but `PossibleValues` field is empty.

**Comment by petervwyatt** [comment] 2022-02-05 09:42
Thank you for finding and reporting these! 

The only one I am unsure about and you also highlight is unclear in the spec, is `ML` since it is defined to be "_... a maximum on the ratio of the miter length to the line width. When the limit is exceeded, the join is converted from a miter to a bevel_" so would ML==0 mean that a bevel is always done for non-zero width lines??  I think this is work raising/asking over in [pdf-issues](https://github.com/pdf-association/pdf-issues).

I also confirmed that all `ca`/`CA` PossibleValues are now identical.

**Comment by petervwyatt** [comment] 2022-02-05 10:11
Fixed now except for `ML`

**Comment by crlf0710** [comment] 2022-02-05 11:15
For `ML` entry, i opened https://github.com/pdf-association/pdf-issues/issues/154 . 

Personally now i'm inclined to think the correct range is `[fn:Eval(@ML>=1)]` (consistente with PostScript).

**Comment by petervwyatt** [comment] 2022-02-11 03:38
Waiting for resolution of https://github.com/pdf-association/pdf-issues/issues/154 before I close

**Closed** 2022-04-22 09:15 UTC
